#!/usr/bin/env bash
# shellcheck shell=bash
# vi:ft=sh fdm=marker ts=2 sw=2 et

# Test runner for dotfiles.
#
# Usage:
#   ./test/run [test_file]
#
# Description:
#   Run all test files located in 'test' directory
#   if no [test_file] is supplied.

TEST_DIRECTORY="$(cd "$(dirname "$0")" && pwd)"
TEST_DEPS_DIR="${TEST_DIRECTORY}/../test_lib"
export TEST_DEPS_DIR
export TEST_DIRECTORY

if [[ -z "${DOTFILES_BASH_DIR:-}" ]]; then
  DOTFILES_BASH_DIR=$(cd "${TEST_DIRECTORY}" && dirname "$(pwd)") \
    && export DOTFILES_BASH_DIR
fi

git submodule init && git submodule update

function main() {
  if [[ -z ${1:-} ]]; then
    # shellcheck disable=2206
    TEST_DIRS=(${TEST_DIRECTORY}/{install,Bash})
  else
    TEST_DIRS=("${1:-}")
  fi

  # shellcheck disable=SC2294
  eval "${TEST_DEPS_DIR}"/bats-core/bin/bats \
    ${CI:+--tap} --recursive "${TEST_DIRS[@]}"
}

main "$@"
