#!/usr/bin/env bash
# run-alias: run local shell functions and tmux custom command alias
# usage: run-alias [COMMAND] [OPTION]
# [!] [OPTION] will depend on local function and/or command alias.

# 1.) command-alias - custom tmux specific commands.
# 2.) tmux commands - commands that are listed in 'tmux list-commands'.
# 3.) local shell functions - shell functions that is ported for tmux.
# ----------------------------------------------------------------
# [] 1.) command parsing.
# ----------------------------------------------------------------
#
# if command exists and is no duplicate, execute command.
#
# if command exists but has duplicate,
#   - display a message and return an exit code.
#
# if command doesn't exists but has partially matched.
#   - display a message and return an exit code.
#
# if command doesn't exists and has no matched,
#  - display a message and return an exit code.

function run-alias() {
  cmd="$1"
  if [[ $(commands | grep -xc "${cmd}") -eq 1 ]]; then
    tmux "${cmd}"
  fi
}

function commands() {
  declare -ar CMDS=(
    "$(tmux list-commands | cut -d' ' -f1)"
    "$(ls "${TMUX_SCRIPTS}")")
  echo "${CMDS[@]}" | tr ' ' '\n'
}

run-alias "$@"
