#!/usr/bin/env bash

# vertically split tmux window

source "$HOME/Projects/dotfiles/tmux/lib.sh"

function main() {
  local name
  name="$(basename "${0}")"
  eval "tmux set -s command-alias[55] ${name} -hc"
  echo ${name}
  echo "$(_get_tty)"
}

# function _get_args() {

# }

main
display '#{@window_current_path}'
