#!/usr/bin/env bash
# shellcheck shell=bash
# vi:ft=sh fdm=marker ts=2 sw=2 et
#
# Warning: this file is generated by Dotfiles Bash,
# all local changes to this file will be overrwritten.
# Write all your local code to ~/.local.bashrc.

# If not running interactively, don't do anything
case $- in
*i*) ;;
*) return ;;
esac

# Path to Dotfiles and Bash directory.
export DOTFILES="{{DOTFILES}}"
export DOT_BASH="{{DOTFILES}}/Bash"

# Don't check mail when opening terminal.
unset MAILCHECK

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# larger history (default: 500)
HISTSIZE=20000
HISTFILESIZE=20000

# enable color support of ls and also add handy aliases.
if [[ -x "/usr/bin/dircolors" ]]; then

  if [[ -r ~/.dircolors ]]; then
    eval "$(dircolors -b ~/dircolors)" ||
      eval "$(dircolors -b)"
  fi

  alias dir="dir --color=always"
  alias ls="ls --color=always"
  alias vdir="vdir --color=always"

  alias grep="grep --color=always"
  alias fgrep="fgrep --color=always"
  alias egrep="egrep --color=always"
fi

# Load dotfiles Bash.
source "${DOT_BASH}/bash_init.sh"
