#!/usr/bin/env bash

#------------------------------------------
#             Custom commands             |
#------------------------------------------

alias path='printf "%b\n" "${PATH//:/\\n}"'          # Print PATH env neatly.
alias bashopts='printf "%b\n" "${BASHOPTS//:/\\n}"'  # Show bashopts env neatly.
alias brestart="sudo /etc/init.d/bluetooth restart"  # Restart bluetooth.
alias mom='ps --no-headers -o comm "${PPID}"'      # which process spawns the shell?
alias todo="grep --recursive 'TOD[O]: '"         # List all todo comments.
alias fixme="grep --recursive 'FIXM[E]: '"     # List all fixme comments.
alias cwd='printf '%s' "${PWD##*/}"'         # Print current working directory.
alias pst="xclip -out"                       # Print xclip selection.
alias open="xdg-open ."
alias reload="exec \${SHELL}"             # Reload the shell.
alias e="exit"                            # Exit the shell.

#------------------------------------------
#             Neovim Editor               |
#------------------------------------------

# TODO: Make this load multiple files.
# Start neovim without plugin but with basic keybindings.
alias nnvim="nvim -u \
    /home/devs/Projects/dotfiles/nvim/components/keybindings.vim"


#------------------------------------------
#              Git commands               |
#------------------------------------------

# git log - Show commit logs.

alias lg="git log --oneline --graph -20"
#                   │         │      └─ Limit output to 20 lines.
#                   │         └─  Display text-based graphical commit history.
#                   └─ Shorthand for --pretty=oneline --abbrev-commit.

# git status - Show the working tree status as 'short-format'.

alias gs="git status --short"     # Staged and untracked files.
alias gsi="gs --ignored"          # Status with ignored files.

# git ls-files - Show info about files in index and the working tree.

alias gli="git ls-files -o -i --exclude-standard"
#                        │  │   └─ Use standard ignore rules.
#                        │  └── Show only ignored files.
#                        └─ Show other (i.e. untracked) files in the output.

# git show - Show one or more objects (blobs, trees, tags, and commits).

alias gshow="git show --oneline"  # Show HEAD's log message and diffs.
#                       └─ Shorthand for --pretty=oneline --abbrev-commit.

# git diff - Show changes between the working tree and the index or a tree.

alias gdf="git diff"              # Show uncommited changes

# git commit - Record changes to the repository.

alias gc="git commit"            # Commit all staged file, fire up $EDITOR.
alias gca="gc --all"             # Stage all files, modified and untracked.
alias gcp="gc --patch"           # Choose which hunks/changes to commit.
alias gam="gc --amend"           # Amend changes to the tip of current branch.

# git add - Update index using the current content found in the working tree.

alias ga="git add"           # Add file/s to the index (staging area).
alias gan="ga --dry-run"     # See What would be added and/or will be ignored.
alias gai="ga --interactive" # Stage file interactively to the index.
alias gap="ga --patch"       # Choose which hunks to be added to index.

# git branch - List, create and delete branches.

alias gb="git branch"       # list all local branches
alias gbd="gb --delete"     # Delete given branch.

alias gu="git reset"              # Unstage file in index.

alias grc="git rm --cached"  # Fix not ignoring.

# git reset - Reset current HEAD to the specified state.

# Reset all changes to HEAD.
alias gr="git reset"

# Delete all uncommited changes to 'working tree' and 'index'
alias grh="gr --hard HEAD"

# Delete all uncommitted changes to index (retain working directory).
alias grs="gr --soft HEAD"

# Delete last commit, index and uncommited changes to working tree.
alias grh1="gr --hard HEAD~1"

# Delete last commit and indexed changes but retain working tree.
alias hrs1="gr --soft HEAD~1"

# Unstaged a file.
alias grf="git reset HEAD --"

#------------------------------------------
#             System commands             |
#------------------------------------------

alias sudo='sudo '                     # Allow aliases to be `sudo`ed.
#alias vim='$EDITOR '                  # Expand from default editor.
alias rm='rm '                         # Allow aliases to be `rm`ed.
alias vifm='vifm '                     # Allow alias expansion for vifm paths.
alias which="which -a"                 # Always show all matching pathnames.

# Sort, list and show hiden files/dirs with colored listing.
alias ls='lsc --almost-all --classify --group-directories-first '
alias dir='dr --almost-all --classify --group-directories-first '

#------------------------------------------
#     Files and directories shortcuts     |
#------------------------------------------

# Frequently used directories.
alias home="~"
alias p="~/Projects"
alias dot="~/Projects/dotfiles"
alias dt="~/Desktop"
alias m="~/Music"
alias dl="~/Downloads"
alias d="~/Documents"
alias et="/etc"

# ------------------------------------------------------------------
# Node version manager
# ------------------------------------------------------------------
alias npmlg="npm list --global --depth 0"
alias nig="npm install --global"
alias nid="npm install --save-dev"
alias nr="npm run"

# ------------------------------------------------------------------
# Gulp task manager
# ------------------------------------------------------------------
alias gl="gulp"
