#!/usr/bin/env bash

# Enable capslock as backspace and double shift as capslock.
alias k="setxkbmap -option caps:backspace && setxkbmap -option shift:both_capslock"

# print alias neatly.
alias path='printf "%b\n" "${PATH//:/\\n}"'

# System commands
alias brestart="sudo /etc/init.d/bluetooth restart"

# Git shortcuts
alias gl="git log --pretty=oneline --max-count=20 --graph --abbrev-commit"
alias gs="git status --short"
alias gshow="git show"

# Frequently used directories shortcuts.
alias home="~"
alias p="~/Projects"
alias dt="~/Desktop"
alias m="~/Music"
alias dl="~/Downloads"
alias d="~/Documents"
alias et="/etc"
