#!/usr/bin/env bash

# Enable color support.
if [ -x /usr/bin/dircolors ]; then

  if test -r ~/.dircolors; then
    eval "$(dircolors -b ~/.dircolors)"
  fi

  alias dir="dir --color=auto"
  alias egrep="egrep --color=auto"
  alias fgrep="fgrep --color=auto"
  alias grep="grep --color=auto"
  alias ls="ls --color=auto"
  alias vdir="vdir --color=auto"

fi

