#!/usr/bin/env bash
function main() {
  # This is probably set already.
  XDG_CONFIG_HOME="$HOME/.config";    export XDG_CONFIG_HOME
  XDG_DATA_HOME="$HOME/.local/share"; export XDG_DATA_HOME

  declare -a hist_ignore=(
    "bash:"  "fish:"   "zsh:"   "dash:"
    "exit:"  "logout:" "clear:"
    "pushd:" "popd:"   "rm:"
    "echo:"  "ls:"
  )
  HISTSIZE=500     # (default: 500)
  HISTFILESIZE=500 # (default: 500)
  HISTCONTROL=ignorespace:erasedups
  HISTIGNORE="$(printf %s "${hist_ignore[@]}")"

  # shellcheck disable=SC2155
  export EDITOR="$( command -v nvim || command -v vim )"
  export MANWIDTH=96

  _set_golang_envars
  _set_prompts_envar
  _set_nvim_manpager
  _set_less_envars
  _set_shellcheck_envars
  _set_fzf_envars

  cleanup && unset -f cleanup
}

function _set_golang_envars() {
! printenv PATH | grep '/usr/local/go/bin' &> /dev/null \
  && PATH="$PATH:/usr/local/go/bin"
! printenv PATH | grep "$(go env GOPATH)" &> /dev/null \
  && PATH="$PATH:$(go env GOPATH)/bin"
}

function _set_prompts_envar() {
  declare -a ps1=(
    "\\[${shade}\\]"
    "\$( __exit_status )"      # last command exit code
    "\\[${bold}\\]"
    "\\[${cyan}\\]"
    "\$( __pwd \"\\W\" )"      # current working directory
    "\\[${reset}\\]"
    "\$( __repo \"(\" \")\" )"
    "\\[${pink}\\]"            # command color
    "\\n"                      # newline
    "\\$ "                     # user privilege
  )

  PS1="\\n$(printf %s "${ps1[@]}")"
  PS2="\\[${pink}\\]\\$ $(trap __colorize_stdout DEBUG)"
}

function _set_nvim_manpager() {
  ! [ "$(command -v nvim)" ] && return
  declare -ag args=(-c "'set ft=man'")
  export MANPAGER="nvim --noplugin ${args[*]}"
}

function _set_less_envars() {
  # @note: exporting LESS will pagerize some git commands and aliases,
  # be sure to set "core.pager" and/or "pager.<cmd/alias>" accordingly.
  export LESS="--quiet --raw-control-chars --ignore-case"
}

function _set_shellcheck_envars() {
  ! [ "$(command -v shellcheck)" ] && return
  declare -a shellcheck_exclude=(
    "SC1090" # don't follow external sources.
  )
  declare -a shellcheck_opts=(
    "--shell=bash"
    "--exclude=$(printf %s "${shellcheck_exclude[@]}")"
  )
  export SHELLCHECK_OPTS="${shellcheck_opts[*]}"
}

function _set_fzf_envars() {
  declare -a fzf_bindkeys=(
    "ctrl-e:preview-down+preview-down," # vim-like preview-scroll-down by 2 lines.
    "ctrl-y:preview-up+preview-up,"     # vim-like preview-scroll-up by 2 lines.
    "ctrl-space:accept"                 # additional accept key.
  )
  declare -a fzf_opts=(
    "--ansi"
    "--bind=$(printf %s "${fzf_bindkeys[@]}")"
    "--margin=0,0,1"
    "--multi"
    "--height=20"
    "--no-bold"
    "--reverse"
    "--inline-info"
    "--header="
  )
  declare -a fzf_cmd=(
    "ag"                 # The Silver Searcher.
    "--skip-vcs-ignores" # include files ignored by VCS.
    "--hidden"           # include hidden files.
    "--ignore .git/"     # exlude ".git/" directory.
    "-g ''"              # print filenames.
  )
  export FZF_DEFAULT_COMMAND="${fzf_cmd[*]}"
  export FZF_DEFAULT_OPTS+="${fzf_opts[*]}"
}

function cleanup() {
  unset -f _set_golang_envars
  unset -f _set_prompts_envar
  unset -f _set_nvim_manpager
  unset -f _set_less_envars
  unset -f _set_shellcheck_envars
  unset -f _set_fzf_envars
}

main && unset -f main
