#!/usr/bin/env bash

# Set Neovim as the default editor.
export EDITOR='vim '

# Neovim ENV, used to locate various files, such as the user's init.vim.
#export VIM="/usr/share/$EDITOR"

# fzf prompt always at the bottom.
export FZF_DEFAULT_OPTS='--no-height --no-reverse'

# start fzf on a tmux split pane.
export FZF_TMUX=1

# Set default term.
export TERM="xterm-256color"

 # TODO: This should have a environmental path.
# Define local inputrc file.
export INPUTRC="/home/devs/Projects/dotfiles/bash/inputrc"

# Dotfiles executables.
export PATH="$PATH:/home/devs/Projects/dotfiles/bin"
