#!/usr/bin/env bash

# Set Neovim as the default editor.
export EDITOR="/usr/bin/nvim"

# --------------------------------------
#           Bash Variables              |
# --------------------------------------

export HISTFILESIZE=10000   # Increase history line limit (default 500).
export HISTSIZE=10000      # Increase command history limit (default 500).
export HISTCONTROL=ignoreboth:erasedups # Innore duplicate commands and spaces.
export INPUTRC="$HOME/Projects/dotfiles/bash/inputrc" # Local inputrc file.
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND" # One history for all.

# Dont add to history file.
export HISTIGNORE="bash:exit:pwd:dir:dirs:ls:clear:echo:man *"

# Dotfiles executables.
if ! printenv PATH | grep 'dotfiles' &> /dev/null; then
  PATH="$HOME/Projects/dotfiles/bin:$PATH"
fi

# Set vim config for `fc` command.
export FCEDIT="$EDITOR -u /home/devs/Projects/dotfiles/nvim/fcedit.vim"
# --------------------------------------
#            FZF Variables              |
# --------------------------------------

export FZF_DEFAULT_OPTS='--no-reverse'      # Prompt always at the bottom.
export FZF_DEFAULT_OPTS+=' --border'        # Show top and bottom border.
export FZF_DEFAULT_OPTS+=' --no-bold'       # Disable bold characters.

export FZF_TMUX=1                           # Use tmux split-pane if possible.

# Set default term.
export TERM="xterm-256color"


# --------------------------------------
#            Man Variables.             |
# --------------------------------------

# Don't clear the screen after quitting a `man` page.
export MANPAGER="less --no-init"

