#!/usr/bin/env bash

# Create directory and enter it.
function md() {

  local dir="${1}"

  mkdir "${dir}" && cd "${dir}" || return

}

# Colorized `cat` output with linenumbers in `less` pager.
function hicat() {

  pygmentize -g "$1" | cat --number | less --RAW-CONTROL-CHARS

}
