#!/usr/bin/env bash

# Start tmux a tmux session with base directory.
function tmx() {

  local session_name=""
  local session_base_dir=""

  session_name="${PWD##*/}"
  session_base_dir="$(pwd)"

  # Create session.
  tmux new -s "${session_name}" -d

  # Set base directory (for statusline shell scripts).
  tmux setenv __base_dir__ "${session_base_dir}"
  
  tmux attach
  
}

# Create directory and enter it.
function md() {

  local dir="${1}"

  mkdir "${dir}" && cd "${dir}" || return

}

# Colorized `cat` output with linenumbers in `less` pager.
function hicat() {

  local file="${1}"
  local filesize=""

  filesize="$(pygmentize -g "${file}" | wc -l)"

  if [ "$filesize" -gt "$(tput lines | awk '{print $file-3}')" ]; then
    pygmentize -g "${file}" | cat --number | less --RAW-CONTROL-CHARS
  else
    pygmentize -g "${file}" | cat --number
  fi

}

# Cd into the current directory after quiting vifm.
vifm() {

  local dest=""
  dest="$(command vifm --choose-dir -)"

  if [ -z "$dest" ]; then
    echo 'Directory picking cancelled/failed'
    return 1
  fi

  cd "$dest" || return
}
