#!/usr/bin/env bash

# ------------------------------------------------------------------
# lazyload nvim
# ------------------------------------------------------------------
# Modified version of @fl0w's gist
# https://gist.github.com/fl0w/07ce79bd44788f647deab307c94d6922
function lazynvm() {
  unset -f nvm node npm npx
  export NVM_DIR=~/.nvm
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
  if [ -f "$NVM_DIR/bash_completion" ]; then
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
  fi
}

function nvm() {
  lazynvm
  nvm "$@"
}

function node() {
  lazynvm
  node "$@"
}

function npm() {
  lazynvm
  npm "$@"
}

function npx() {
  lazynvm
  npx "$@"
}

# ------------------------------------------------------------------
# md - create directory and enter it
# ------------------------------------------------------------------
function md() {
  local dir="$1"
  mkdir "$dir" && cd "${dir}" || return
}

# ------------------------------------------------------------------
# fshow - git commit browser (fzf)
# ------------------------------------------------------------------
function fshow() {
  local output shas sha query key
  while output=$(
          git log --graph --color=always \
            --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" "$@" |
          fzf --ansi --multi --no-sort --reverse --query="$query" \
            --print-query --expect=ctrl-d --toggle-sort=\`
        ); do
    query=$(head -1 <<< "$output")
    key=$(head -2 <<< "$output" | tail -1)
    shas=$(sed '1,2d;s/^[^a-z0-9]*//;/^$/d' <<< "$output" | awk '{print $1}')
    [ -z "$shas" ] && continue
    if [ "$key" = ctrl-d ]; then
      git diff --color=always "$shas" | $MANPAGER -R
    else
      for sha in $shas; do
        git show --color=always "$sha" | $MANPAGER -R
      done
    fi
  done
}
