#!/usr/bin/env bash

# Enable line editing using vi style.
set -o vi

shopt -s no_empty_cmd_completion   # No auto-completion on empty line.
shopt -s autocd                    # Allow omitting `cd` to directory names.
shopt -s cdspell                   # Auto-correct typos in path names.
shopt -s nocaseglob                # Case-insensitive pathname globbing.
shopt -s checkwinsize              # Update `LINES` and `COLUMNS` if needed.
shopt -s cmdhist                   # Save multi-line command in one hist entry.
shopt -s dotglob                   # Include (.)files in file globbing.
shopt -s histappend                # Append to history rather than override.
