#!/usr/bin/env bash

# shellcheck disable=SC1090
source "$HOME/Projects/dotfiles/tmux/lib.sh"

function main() {

  # executables
  if ! printenv PATH | grep "tmux/bin" &> /dev/null; then
    command tmux setenv -g "PATH" "$PATH:$HOME/Projects/dotfiles/tmux/bin"
  fi

  window-option "@window_current_path" "#{pane_current_path}"
  session-name "#{b:pane_current_path}"

  setenv

}

function setenv() {
  local fzf
  # fzf="$(echo "$FZF_DEFAULT_OPTS")"

  # command tmux display -p "$FZF_DEFAULT_OPTS"
  # echo $FZF_DEFAULT_OPTS
}

function git-stream-status() {
  local working_dir

  working_dir="$( display '#{@window_current_path}' )"

  tmux set status-right "$working_dir"
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# [?] for debugging library file
# call this function to debug the library script inside tmux terminal.

function testing() {
  # source library file.
  command tmux set -ag default-command " --rcfile $HOME/Projects/dotfiles/tmux/lib.sh"
}
# testing

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

main
