#!/usr/bin/env bash
#
# shellcheck disable=SC1090

function main() {
  init_sources
}

function init_sources() {
  declare -ra source_files=(
    "tmux/command-aliases/init.aliases.tmux"
    "tmux/keybindings/init.keybindings.tmux"
    "tmux/statusbar/simple/simple.status.tmux"
    "_localrc/tmuxrc.local");

  for file in ${source_files[*]}; do
    command tmux source-file "$HOME/Projects/dotfiles/${file}"
  done
  unset file
}

function set_command() {
 local test
}

main
