#!/usr/bin/env bash
# shellcheck shell=bash
# vi:ft=sh fdm=marker ts=2 sw=2 et

function __load_theme() {
  _::source_file \
    "${DOT_BASH}/themes/${BASH_THEME:-default}/${BASH_THEME:-default}.theme.bash"
}

__load_theme \
  && unset -f __load_theme
