#!/usr/bin/env bash
# shellcheck shell=bash
#
# Set up shell variables for Bash

# Prefer US English and use UTF-8 encoding.
LANG="en_US"
LC_ALL="en_US.UTF-8"

# disable mailcheck.
if [[ $( shopt mailwarn | awk '{ print $2 }' ) == 'off' ]]; then
  unset MAILCHECK
fi

# append current sessions history to the history file.
PROMPT_COMMAND=('history -a')

# useful editors.
VISUAL="$(command -v nvim || command -v vim || command -v )"
EDITOR="$(command -v ed || echo "${VISUAL}")"

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# larger history (default: 500)
HISTSIZE=20000
HISTFILESIZE=20000

HISTCONTROL='ignorespace:erasedups';
HISTIGNORE='bash:fish:zsh:dash:exit:logout:clear:pushd:popd:ls:echo';
