#!/usr/bin/env bash
#
# Set up environment variables for:
# rust, android, distribution ruby, environment path, bash history,
# bash prompt, man page, less, shellcheck, fzf, xdg specifications.

function main() {
  set_xdg_specs
  set_path
  set_ruby_distrib_path

  set_manpager
  set_less_envars
  set_shellcheck_envars
  set_rust_envars

  cleanup && unset -f "${FUNCNAME[0]}";
}

function set_rust_envars() {
  _::add_to_path "${HOME}/.cargo/bin";
}

function set_ruby_distrib_path() {
  if [[ -d "${HOME}/.ruby" ]]; then
    GEM_HOME="${HOME}/.ruby";
    _::add_to_path "${GEM_HOME}/bin";
    export GEM_HOME;
  fi
}

function set_path() {
  _::add_to_path "${HOME-}/.yarn/bin"
  _::add_to_path "${HOME-}/symfony/bin"
  _::add_to_path "/usr/local/go/bin"
}

function set_manpager() {
  command -v nvim &> /dev/null || {
    export LESS_TERMCAP_md="${yellow}"; # higlight section titles in manpages
    export MANPAGER='less -X'; # don't clear the screen after quitting a manpage
    return;
  }
  export MANWIDTH=96;
  # set neovim as manpager
  export MANPAGER="nvim -c ':set ft=man'";
  # [?] for faster manpager without plugins uncomment the line below.
  # export MANPAGER="nvim --noplugin -c ':set ft=man'";
}

function set_less_envars() {
  # @note: exporting LESS will pagerize some git commands and aliases,
  # set "core.pager" and/or "pager.<cmd/alias>" to false to avoid this.
  export LESS="--quiet --raw-control-chars --ignore-case";
}

function set_shellcheck_envars() {
  command -v shellcheck &> /dev/null || return;

  declare -ra SHELLCHECK_LOCAL_OPTS=(
    "--shell=bash"
    "--exclude=SC1090" # do not follow external sources
  );

  export SHELLCHECK_OPTS="${SHELLCHECK_LOCAL_OPTS[*]}";
}

function cleanup() {
  unset -f set_path \
           set_ruby_distrib_path;
  unset -f set_hist_envars \
           set_manpager \
           set_less_envars \
           set_shellcheck_envars
  unset -f "${FUNCNAME[0]}";
}

function set_xdg_specs() {
  # This is probably set already.
  declare -xr XDG_CONFIG_HOME="${HOME}/.config" && \
    export XDG_CONFIG_HOME;

  declare -xr XDG_DATA_HOME="${HOME}/.local/share" && \
    export XDG_DATA_HOME;
}

main "$@"
