#!/usr/bin/env bash
# shellcheck shell=bash
# vi:ft=sh fdm=marker ts=2 sw=2 et

# Basic colors

function __ls_colors() {
  if [[ -x "/usr/bin/dircolors" ]]; then

    if [[ -r ~/.dircolors ]]; then
      eval "$(dircolors -b ~/dircolors)"
    fi

    alias dir="dir --color=always"
    alias egrep="egrep --color=always"
    alias fgrep="fgrep --color=always"
    alias grep="grep --color=always"
    alias lscolor="ls --color=always"
    alias vdir="vdir --color=always"
  fi

  LS_COLORS=''
  LS_COLORS+="no=0;39:"   # Global default
  LS_COLORS+="di=0;36:"   # Directory
  LS_COLORS+="ex=0;32:"   # Executable file
  LS_COLORS+="fi=0;39:"   # File
  LS_COLORS+="ec=:"       # Non-filename text
  LS_COLORS+="mi=0;31:"   # Non-existent file pointed to by a symlink
  LS_COLORS+="ln=target:" # Symbolic link
  LS_COLORS+="ow=0;35:"   # Other writable
  LS_COLORS+="or=31;01:"  # Symbolic link pointing to a non-existent file

  export LS_COLORS
}

__ls_colors \
&& unset -f __ls_colors
