#!/usr/bin/env bash

# ------------------------------------------------------------------
# Helper functions for in-house scripts
# ------------------------------------------------------------------
_inside_tmux() {
  local parent
  parent="$(ps --no-headers -o comm "$PPID")"
  if [ "${parent}" = 'tmux: server' ]; then
    return 0
  else
    return 1
  fi
}

main() {
  export -f _inside_tmux
}

main
