#!/usr/bin/env bash

# TODO: get the actual failing command rather than just hard coding.
function __error() {
 if [ "$?" -eq 127 ]; then
   echo -e "[keybindings]: command not found -> $1 "
 else
   echo "[keybindings]: error $?"
 fi
}

bind -x '"\C-n": "vifm &> /dev/null || __error vifm"' # launch a file browser.
