#!/usr/bin/env bash

# enable vi-style line editing
set -o vi

declare -ra options=(
"no_empty_cmd_completion" # no auto-completion on empty line
"autocd"                  # allow omitting `cd` to directory names
"cdspell"                 # auto-correct typos in path names
"nocaseglob"              # case-insensitive pathname globbing
"checkwinsize"            # update `LINES` and `COLUMNS` if needed
"cmdhist"                 # save multi-line command in one hist entry
"cdable_vars"             # if dir is not found, cd to value of variable
"checkhash"               # check if command exists in hashtable before executing
"checkjobs"               # check if there's any jobs before exiting the shell
"dirspell"                # directory auto-correction
"dotglob"                 # include (.)files in file globbing.
"extglob"                 # extended pattern matching in pathname expansion
"failglob"                # if fail to match filenames return expansion error
"globstar"                # ** will match all files and zero more more dir & subdir
"gnu_errfmt"              # set error messages same as GNU error messages format
"histappend"              # append to history rather than override
"histreedit"              # allow readline to re-edit failed history substitution
"histverify"              # allow further modification for history-substitution results
"hostcomplete"            # hostname completion if '@' is being completed
"huponexit"               # send SIGHUP to all jobs when interative login shell exits
"lithist"                 # save multi-line cmd history with embedded newlines
"mailwarn"                # warn if mail has been accessed since the last time it was checked
"nullglob"                # expand patterns with no match to null string
"progcomp_alias"          # completion using the word resulting from expanded alias
"xpg_echo" )              # expand backslash-escape sequences

for opts in ${options[*]}; do
  shopt -s "${opts}"
done
unset opts
