#!/usr/bin/env bash
# -----------------------------------------------------------------------------
#  File:          functions.sh
#  Description:   Helper utility function for easy BASH shell scripting
#  Author:        John Fred Fadrigalan <github.com/cevhyruz>
#  License:       DWTFYWTPL
# -----------------------------------------------------------------------------

# shellcheck disable=SC2231 source=/dev/null

declare DOTFILES_LIBPATH="${HOME}/Projects/dotfiles/bash/lib/lib.bash";

function Profile::init() {
  source "${DOTFILES_LIBPATH}" &> /dev/null || {
    printf "%b" "[Error]: Library file not found.\n"
    return 1;
  }
}

function Profile::load_aliases() {
  _load_bash_components
  lib::source_all_from "/etc/profile.d"
}

# Extra local configuration.
function Profile::load_local() {
  [[ -r "${HOME}/Projects/dotfiles/localrc/local.bashrc" ]] \
    && source "${HOME}/Projects/dotfiles/localrc/local.bashrc";
}

function Profile::main() {
  Profile::init
  Profile::init || {
    return 1;
  };
  Profile::load_local;
  Profile::load_aliases;
}

function _load_bash_components() {
  declare -r bash_dir="${HOME}/Projects/dotfiles/bash"
  declare -ra components=(
    "colors"
    "lib/functions.sh"
    "keybindings"
    "completion/tmux"
    "completion/fzf");

  for file in "${components[@]}";  do
    [ -r "${bash_dir}/${file}" ] \
      && [ -s "${bash_dir}/${file}" ] \
    && source "${bash_dir}/${file}"
  done
  unset file
}

Profile::main "${@}"
