#!/usr/bin/env bash

function _source_bash_files() {

  local file=""

  for file in /etc/profile.d/*; do
    [ -r "$file" ] \
       &&  . "$file"
  done
  unset file

  # Make sure to source fzf after the bash_completion.sh
  # to avoid keybindings conflicts.
  . "/home/devs/Projects/dotfiles/bash/fzf"

  # For local configuration that should
  # not be included in source control.
  if [ -r "/home/devs/Projects/dotfiles/_localrc/local.bashrc" ]; then
      . "/home/devs/Projects/dotfiles/_localrc/local.bashrc"
  fi

}
_source_bash_files
unset -f _source_bash_files
