name: 'BATS'

# Triggers the workflow on push or pull request events but only for the master branch
on: [pull_request, push]

jobs:
  bats-test:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Test code
      run: test/run
