name: 'build'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    strategy:
      matrix:
        neovim: [true, false]
        version: [nightly, stable]
        exclude:
          - neovim: false
            version: stable
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install vim or neovim
      uses: rhysd/action-setup-vim@v1
      id: vim
      with:
        neovim: ${{ matrix.neovim }}

    - name: Test code
      run: test/run

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install shfmt
      run: GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt

    - name: Install shellcheck
      run: brew install shellcheck

    - name: Install pre-commit
      run: python3 -m pip install pre-commit==2.3.0

    - name: Run lint
      run: ./lint.sh

  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install Ruby dependencies
      run: bundle update --bundler && bundle install

    - name: Run script
      run: bashcov test/run

    - name: Upload reports to Codecov
      run: bash <(curl -s https://codecov.io/bash) -Z
