name: 'build'

on: [pull_request, push]

jobs:
  bats-test:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Test code
      run: test/run

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install shfmt
      run: GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt
    - name: Install shellcheck
      run: brew install shellcheck
    - name: Install pre-commit
      run: python3 -m pip install -r pre-commit==2.3.0
    - name: Run lint
      run: ./lint.sh
